/**
 * Email send helper — single entry point for every outgoing message.
 *
 * Wraps the Resend SDK with:
 *   - Graceful no-op when RESEND_API_KEY isn't configured (instead of
 *     throwing, returns { ok: false, reason: "not_configured" }). Lets
 *     the rest of the system keep working when email is offline.
 *   - Consistent return shape so callers can branch on success without
 *     dealing with thrown errors / network exceptions.
 *   - Category tagging via Resend's tags feature for later analytics
 *     ("how many renewal reminders did we send last week?").
 *
 * Every caller — renewal cron, commission notification, invite — goes
 * through this single helper so any future cross-cutting concern
 * (rate limiting, suppression list checks, unsubscribe handling)
 * lives in exactly one place.
 */

import { getEmailFrom, getResendClient } from "./client";

export interface SendEmailOptions {
  /** Single recipient or array — Resend accepts both. */
  to: string | string[];
  subject: string;
  /** HTML body. Plain-text version is auto-generated by Resend. */
  html: string;
  /** Optional category tag for analytics ("renewal_reminder", "invite", etc.). */
  category?: string;
  /** Optional Reply-To address — defaults to no reply-to header. */
  replyTo?: string;
}

export type SendEmailResult =
  | { ok: true; id: string }
  | { ok: false; reason: "not_configured" | "send_failed"; error?: string };

/**
 * Send an email via Resend. Never throws — returns a discriminated
 * union the caller can pattern-match on.
 */
export async function sendEmail(
  opts: SendEmailOptions,
): Promise<SendEmailResult> {
  const client = getResendClient();
  if (!client) {
    return { ok: false, reason: "not_configured" };
  }
  try {
    const { data, error } = await client.emails.send({
      from: getEmailFrom(),
      to: opts.to,
      subject: opts.subject,
      html: opts.html,
      replyTo: opts.replyTo,
      tags: opts.category
        ? [{ name: "category", value: opts.category }]
        : undefined,
    });
    if (error || !data?.id) {
      return {
        ok: false,
        reason: "send_failed",
        error: error?.message || "Unknown Resend error",
      };
    }
    return { ok: true, id: data.id };
  } catch (err) {
    return {
      ok: false,
      reason: "send_failed",
      error: err instanceof Error ? err.message : String(err),
    };
  }
}
