"use client";

import { useState } from "react";
import { ArrowLeft, ArrowRight, Check, Languages, Sparkles } from "lucide-react";
import { Modal } from "@/components/ui/Modal";
import { Button } from "@/components/ui/Button";
import { Select } from "@/components/ui/Select";
import { ONBOARDING_QUESTIONS, AI_COPY_MODES } from "@/lib/constants";
import { useProfileStore } from "@/store/profileStore";
import { applyGeneratedContent } from "@/lib/ai/generators";
import { toast } from "@/store/uiStore";
import { cn } from "@/lib/utils";
import type {
  AICopyMode,
  AILanguage,
  AIOnboardingAnswers,
  GeneratedProfileContent,
} from "@/types";

const TOTAL = ONBOARDING_QUESTIONS.length + 1; // + style step

export function AIGenerateModal({
  open,
  onClose,
}: {
  open: boolean;
  onClose: () => void;
}) {
  const profile = useProfileStore((s) => s.profile);
  const setProfile = useProfileStore((s) => s.setProfile);

  const [step, setStep] = useState(0);
  const [answers, setAnswers] = useState<Record<string, string>>({});
  const [tone, setTone] = useState<AICopyMode>("professional");
  const [language, setLanguage] = useState<AILanguage>("english");
  const [generating, setGenerating] = useState(false);
  /* Once generation succeeds we don't apply the content immediately —
     we hold it here and let the user pick their preferred headline +
     bio variant first. `null` = no variants pending. */
  const [pendingContent, setPendingContent] =
    useState<GeneratedProfileContent | null>(null);
  const [pickedHeadline, setPickedHeadline] = useState<string>("");
  const [pickedBio, setPickedBio] = useState<string>("");

  const isStyleStep = step === ONBOARDING_QUESTIONS.length;
  const question = ONBOARDING_QUESTIONS[step];

  const reset = () => {
    setStep(0);
    setAnswers({});
    setGenerating(false);
    setPendingContent(null);
    setPickedHeadline("");
    setPickedBio("");
  };

  const close = () => {
    if (generating) return;
    onClose();
    setTimeout(reset, 250);
  };

  const applyPicked = () => {
    if (!profile || !pendingContent) return;
    const finalContent: GeneratedProfileContent = {
      ...pendingContent,
      headline: pickedHeadline || pendingContent.headline,
      bio: pickedBio || pendingContent.bio,
    };
    setProfile(applyGeneratedContent(profile, finalContent));
    toast.success("Your profile is ready — preview it on the right.");
    close();
  };

  const generate = async () => {
    if (!profile) return;
    setGenerating(true);
    const payload: AIOnboardingAnswers = {
      niche: answers.niche || "",
      company: answers.company || "",
      offer: answers.offer || "",
      targetMarket: answers.targetMarket || "",
      mission: answers.mission || "",
      resultYouHelpAchieve: answers.resultYouHelpAchieve || "",
      brandingStyle: answers.brandingStyle || "",
      tone,
      language,
    };
    try {
      const res = await fetch("/api/ai/generate-profile", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ answers: payload }),
      });
      const json = await res.json();
      if (!res.ok) throw new Error(json.error || "Generation failed");
      const content = json.data as GeneratedProfileContent;
      const headlineVariants = content.headlineVariants ?? [content.headline];
      const bioVariants = content.bioVariants ?? [content.bio];
      const hasChoice = headlineVariants.length > 1 || bioVariants.length > 1;
      if (hasChoice) {
        /* Hand off to the picker step — apply happens on confirm. */
        setPendingContent(content);
        setPickedHeadline(headlineVariants[0] || content.headline);
        setPickedBio(bioVariants[0] || content.bio);
        setGenerating(false);
        return;
      }
      /* No variants returned (older flow or single-option mock) — apply directly. */
      setProfile(applyGeneratedContent(profile, content));
      toast.success(
        json.usedAI
          ? "Your profile was generated by AI!"
          : "Generated with starter copy — add a Gemini key for full AI.",
      );
      close();
    } catch (err) {
      toast.error(
        err instanceof Error ? err.message : "AI generation failed.",
      );
      setGenerating(false);
    }
  };

  return (
    <Modal
      open={open}
      onClose={close}
      title="AI Profile Generator"
      description="Answer a few questions — AI writes your whole profile."
    >
      {/* Progress */}
      <div className="mb-4 flex gap-1">
        {Array.from({ length: TOTAL }).map((_, i) => (
          <span
            key={i}
            className={cn(
              "h-1 flex-1 rounded-full transition-colors",
              i <= step ? "bg-electric-500" : "bg-white/10",
            )}
          />
        ))}
      </div>

      {generating ? (
        <div className="flex flex-col items-center py-10 text-center">
          <span className="flex h-14 w-14 animate-pulse items-center justify-center rounded-2xl bg-brand-gradient shadow-glow-blue">
            <Sparkles className="h-7 w-7 text-white" />
          </span>
          <p className="mt-4 font-display text-sm font-semibold text-white">
            Writing your profile…
          </p>
          <p className="mt-1 text-xs text-white/45">
            Generating headline, bio, CTAs and credibility copy.
          </p>
        </div>
      ) : pendingContent ? (
        <div className="space-y-5 pb-2">
          <div>
            <p className="font-display text-sm font-semibold text-white">
              Pick your headline
            </p>
            <p className="mt-0.5 text-xs text-white/45">
              The AI wrote a few angles — choose the one that sounds most like you.
            </p>
            <div className="mt-2.5 space-y-1.5">
              {(pendingContent.headlineVariants ?? [pendingContent.headline]).map(
                (v, i) => (
                  <VariantOption
                    key={`h-${i}`}
                    text={v}
                    selected={pickedHeadline === v}
                    onSelect={() => setPickedHeadline(v)}
                  />
                ),
              )}
            </div>
          </div>
          <div>
            <p className="font-display text-sm font-semibold text-white">
              Pick your bio
            </p>
            <p className="mt-0.5 text-xs text-white/45">
              You can always edit it after — this is just the starting point.
            </p>
            <div className="mt-2.5 space-y-1.5">
              {(pendingContent.bioVariants ?? [pendingContent.bio]).map((v, i) => (
                <VariantOption
                  key={`b-${i}`}
                  text={v}
                  selected={pickedBio === v}
                  onSelect={() => setPickedBio(v)}
                />
              ))}
            </div>
          </div>
        </div>
      ) : isStyleStep ? (
        <div className="space-y-4 pb-2">
          <Select
            label="Copy tone"
            value={tone}
            onChange={(v) => setTone(v as AICopyMode)}
            options={AI_COPY_MODES.map((m) => ({
              value: m.id,
              label: m.label,
            }))}
          />
          <div>
            <p className="mb-1.5 text-xs font-medium text-white/65">
              Language
            </p>
            <div className="flex gap-2">
              {(["english", "taglish"] as AILanguage[]).map((lang) => (
                <button
                  key={lang}
                  onClick={() => setLanguage(lang)}
                  className={cn(
                    "flex flex-1 items-center justify-center gap-1.5 rounded-xl border py-2.5 text-sm font-medium capitalize",
                    language === lang
                      ? "border-electric-500 bg-electric-500/15 text-electric-300"
                      : "border-white/10 text-white/55",
                  )}
                >
                  <Languages className="h-4 w-4" />
                  {lang}
                </button>
              ))}
            </div>
            {language === "taglish" && (
              <p className="mt-1.5 text-xs text-white/40">
                Natural Filipino-English mix — perfect for PH prospects.
              </p>
            )}
          </div>
        </div>
      ) : (
        <div className="pb-2">
          <p className="font-display text-base font-semibold text-white">
            {question.question}
          </p>
          <textarea
            autoFocus
            value={answers[question.key] || ""}
            onChange={(e) =>
              setAnswers((a) => ({ ...a, [question.key]: e.target.value }))
            }
            placeholder={question.placeholder}
            rows={3}
            className="mt-3 w-full resize-none rounded-xl border border-white/10 bg-white/[0.03] p-3 text-sm text-white placeholder:text-white/30 outline-none focus:border-electric-500/60"
          />
        </div>
      )}

      {!generating && (
        <div className="mt-4 flex gap-2">
          {pendingContent ? (
            <Button
              fullWidth
              onClick={applyPicked}
              leftIcon={<Check className="h-4 w-4" />}
            >
              Use these
            </Button>
          ) : (
            <>
              {step > 0 && (
                <Button
                  variant="outline"
                  onClick={() => setStep((s) => s - 1)}
                  leftIcon={<ArrowLeft className="h-4 w-4" />}
                >
                  Back
                </Button>
              )}
              {isStyleStep ? (
                <Button
                  fullWidth
                  onClick={generate}
                  leftIcon={<Sparkles className="h-4 w-4" />}
                >
                  Generate my profile
                </Button>
              ) : (
                <Button
                  fullWidth
                  onClick={() => setStep((s) => s + 1)}
                  rightIcon={<ArrowRight className="h-4 w-4" />}
                >
                  {step === ONBOARDING_QUESTIONS.length - 1 ? "Almost done" : "Next"}
                </Button>
              )}
            </>
          )}
        </div>
      )}
    </Modal>
  );
}

function VariantOption({
  text,
  selected,
  onSelect,
}: {
  text: string;
  selected: boolean;
  onSelect: () => void;
}) {
  return (
    <button
      type="button"
      onClick={onSelect}
      className={cn(
        "flex w-full items-start gap-2.5 rounded-xl border p-3 text-left text-sm transition-colors",
        selected
          ? "border-electric-500/70 bg-electric-500/10 text-white"
          : "border-white/10 bg-white/[0.02] text-white/70 hover:border-white/20 hover:text-white",
      )}
    >
      <span
        className={cn(
          "mt-0.5 flex h-4 w-4 shrink-0 items-center justify-center rounded-full border",
          selected ? "border-electric-400 bg-electric-500" : "border-white/25",
        )}
      >
        {selected && <Check className="h-2.5 w-2.5 text-white" />}
      </span>
      <span className="flex-1 leading-snug">{text}</span>
    </button>
  );
}
