"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowLeft, ArrowRight, Languages, Sparkles } from "lucide-react";
import { Modal } from "@/components/ui/Modal";
import { Button } from "@/components/ui/Button";
import { Select } from "@/components/ui/Select";
import { useAuth } from "@/hooks/useAuth";
import { saveFunnel } from "@/lib/firebase/firestore";
import { AI_FUNNEL_TYPES, funnelFromGenerated } from "@/lib/funnels";
import { AI_COPY_MODES } from "@/lib/constants";
import { cn } from "@/lib/utils";
import { toast } from "@/store/uiStore";
import type {
  AICopyMode,
  AIFunnelAnswers,
  AILanguage,
  GeneratedFunnelContent,
} from "@/types";

const QUESTIONS = [
  {
    key: "goal" as const,
    q: "What are you promoting or recruiting for?",
    placeholder: "e.g. A wellness business opportunity",
  },
  {
    key: "audience" as const,
    q: "Who is your target market?",
    placeholder: "e.g. Busy moms looking for extra income",
  },
  {
    key: "result" as const,
    q: "What result do you help them achieve?",
    placeholder: "e.g. A side income of ₱20k+/month",
  },
];

/* funnel-type step + 3 questions + style step */
const TOTAL = QUESTIONS.length + 2;

export function AIFunnelModal({
  open,
  onClose,
  takenSlugs,
}: {
  open: boolean;
  onClose: () => void;
  takenSlugs: string[];
}) {
  const router = useRouter();
  const { account } = useAuth();

  const [step, setStep] = useState(0);
  const [funnelType, setFunnelType] = useState(AI_FUNNEL_TYPES[0].id);
  const [answers, setAnswers] = useState<Record<string, string>>({});
  const [tone, setTone] = useState<AICopyMode>("recruiting");
  const [language, setLanguage] = useState<AILanguage>("english");
  const [generating, setGenerating] = useState(false);

  const isTypeStep = step === 0;
  const isStyleStep = step === TOTAL - 1;
  const question = !isTypeStep && !isStyleStep ? QUESTIONS[step - 1] : null;

  const reset = () => {
    setStep(0);
    setAnswers({});
    setFunnelType(AI_FUNNEL_TYPES[0].id);
    setTone("recruiting");
    setLanguage("english");
    setGenerating(false);
  };

  const close = () => {
    if (generating) return;
    onClose();
    setTimeout(reset, 250);
  };

  const generate = async () => {
    if (!account) return;
    const type =
      AI_FUNNEL_TYPES.find((t) => t.id === funnelType) ?? AI_FUNNEL_TYPES[0];
    const payload: AIFunnelAnswers = {
      funnelType: type.label,
      goal: answers.goal || "",
      audience: answers.audience || "",
      result: answers.result || "",
      tone,
      language,
    };
    setGenerating(true);
    try {
      const res = await fetch("/api/ai/generate-funnel", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ answers: payload }),
      });
      const json = await res.json();
      if (!res.ok) throw new Error(json.error || "Generation failed");

      const content = json.data as GeneratedFunnelContent;
      const funnel = funnelFromGenerated(account.uid, content);
      /* Keep the slug unique among the user's existing funnels. */
      const taken = new Set(takenSlugs);
      let slug = funnel.slug;
      let n = 2;
      while (taken.has(slug)) slug = `${funnel.slug}-${n++}`;
      funnel.slug = slug;

      await saveFunnel(funnel);
      toast.success(
        json.usedAI
          ? "Funnel generated by AI!"
          : "Generated with starter copy — add a Gemini key for full AI.",
      );
      router.push(`/funnels/${funnel.id}`);
    } catch (err) {
      toast.error(err instanceof Error ? err.message : "AI generation failed.");
      setGenerating(false);
    }
  };

  return (
    <Modal
      open={open}
      onClose={close}
      title="AI Funnel Generator"
      description="Answer a few questions — AI writes your funnel."
    >
      <div className="mb-4 flex gap-1">
        {Array.from({ length: TOTAL }).map((_, i) => (
          <span
            key={i}
            className={cn(
              "h-1 flex-1 rounded-full transition-colors",
              i <= step ? "bg-electric-500" : "bg-white/10",
            )}
          />
        ))}
      </div>

      {generating ? (
        <div className="flex flex-col items-center py-10 text-center">
          <span className="flex h-14 w-14 animate-pulse items-center justify-center rounded-2xl bg-brand-gradient shadow-glow-blue">
            <Sparkles className="h-7 w-7 text-white" />
          </span>
          <p className="mt-4 font-display text-sm font-semibold text-white">
            Building your funnel…
          </p>
          <p className="mt-1 text-xs text-white/45">
            Writing each step&apos;s headline, copy and CTA.
          </p>
        </div>
      ) : isTypeStep ? (
        <div className="space-y-2 pb-2">
          <p className="font-display text-base font-semibold text-white">
            What kind of funnel?
          </p>
          {AI_FUNNEL_TYPES.map((t) => (
            <button
              key={t.id}
              onClick={() => setFunnelType(t.id)}
              className={cn(
                "w-full rounded-xl border p-3 text-left transition-colors",
                funnelType === t.id
                  ? "border-electric-500 bg-electric-500/10"
                  : "border-white/10 hover:border-white/20",
              )}
            >
              <p className="text-sm font-semibold text-white">{t.label}</p>
              <p className="mt-0.5 text-xs text-white/45">{t.description}</p>
            </button>
          ))}
        </div>
      ) : isStyleStep ? (
        <div className="space-y-4 pb-2">
          <Select
            label="Copy tone"
            value={tone}
            onChange={(v) => setTone(v as AICopyMode)}
            options={AI_COPY_MODES.map((m) => ({
              value: m.id,
              label: m.label,
            }))}
          />
          <div>
            <p className="mb-1.5 text-xs font-medium text-white/65">Language</p>
            <div className="flex gap-2">
              {(["english", "taglish"] as AILanguage[]).map((lang) => (
                <button
                  key={lang}
                  onClick={() => setLanguage(lang)}
                  className={cn(
                    "flex flex-1 items-center justify-center gap-1.5 rounded-xl border py-2.5 text-sm font-medium capitalize",
                    language === lang
                      ? "border-electric-500 bg-electric-500/15 text-electric-300"
                      : "border-white/10 text-white/55",
                  )}
                >
                  <Languages className="h-4 w-4" />
                  {lang}
                </button>
              ))}
            </div>
          </div>
        </div>
      ) : question ? (
        <div className="pb-2">
          <p className="font-display text-base font-semibold text-white">
            {question.q}
          </p>
          <textarea
            autoFocus
            value={answers[question.key] || ""}
            onChange={(e) =>
              setAnswers((a) => ({ ...a, [question.key]: e.target.value }))
            }
            placeholder={question.placeholder}
            rows={3}
            className="mt-3 w-full resize-none rounded-xl border border-white/10 bg-white/[0.03] p-3 text-sm text-white placeholder:text-white/30 outline-none focus:border-electric-500/60"
          />
        </div>
      ) : null}

      {!generating && (
        /* Smaller buttons (size="sm") + sm: prefix on padding/spacing
           so the Back + Generate combo never overflows the modal
           on the narrowest phones. Back is shrink-0 to keep its
           "Back" label visible — the main button takes the remaining
           space and truncates if absolutely needed. */
        <div className="mt-4 flex items-stretch gap-2">
          {step > 0 && (
            <Button
              variant="outline"
              size="sm"
              onClick={() => setStep((s) => s - 1)}
              leftIcon={<ArrowLeft className="h-4 w-4" />}
              className="shrink-0"
            >
              Back
            </Button>
          )}
          {isStyleStep ? (
            <Button
              fullWidth
              size="sm"
              onClick={generate}
              leftIcon={<Sparkles className="h-4 w-4" />}
            >
              Generate funnel
            </Button>
          ) : (
            <Button
              fullWidth
              size="sm"
              onClick={() => setStep((s) => s + 1)}
              rightIcon={<ArrowRight className="h-4 w-4" />}
            >
              {step === TOTAL - 2 ? "Almost done" : "Next"}
            </Button>
          )}
        </div>
      )}
    </Modal>
  );
}
